services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server